backend:
  name: github
  repo: kirittanna/pf2018

media_folder: /public/assets
public_folder: /assets
display_url: https://pf2018.netlify.com

collections:
  - name: "news"
    label: "News"
    label_singular: "Article"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { name: "path", label: "Path", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - label: "Global"
        name: "global"
        file: "content/global.md"
        fields:
          - { label: "Copyright", name: "copyright", widget: "markdown" }
          - { label: "Disclaimer", name: "disclaimer", widget: "markdown" }
          - label: "Related Sites"
            name: "related-sites"
            widget: "list"
            fields:
              - { label: "Name", name: "relatedName", widget: "string" }
              - { label: "Link", name: "relatedLink", widget: "string" }
              
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Path", name: "path", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Featured"
            name: "featured"
            widget: "list"
            fields:
              - { label: "Name", name: "featureName", widget: "string" }
              - { label: "Intro", name: "featureIntro", widget: "markdown" }
              - { label: "Image", name: "featurePhoto", widget: "image" }
              - { label: "Link", name: "featureLink", widget: "string", required: false }

      - label: "Overview"
        name: "overview"
        file: "content/overview.md"
        fields:
          - { label: "Path", name: "path", widget: "string" }
          - { name: "header", label: "Header", widget: "markdown" }
          - { name: "footer", label: "Footer", widget: "markdown" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "FAQs"
        name: "faqs"
        file: "content/faqs.md"
        fields:
          - { label: "Path", name: "path", widget: "string" }
          - { name: "header", label: "Header", widget: "markdown" }
          - { name: "footer", label: "Footer", widget: "markdown" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Questions"
            name: "questions"
            widget: "list"
            fields:
              - { label: "Question", name: "faq-question", widget: "markdown" }
              - { label: "Answer", name: "faq-answer", widget: "markdown" }

      - label: "Community"
        name: "community"
        file: "content/community.md"
        fields:
          - { label: "Path", name: "path", widget: "string" }
          - { name: "header", label: "Header", widget: "markdown" }
          - { name: "footer", label: "Footer", widget: "markdown" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Events"
            name: "community-events"
            widget: "list"
            fields:
              - { label: "Event Name", name: "eventName", widget: "string" }
              - { label: "Event Image", name: "eventPhoto", widget: "image" }
              - { label: "Event Date", name: "eventDate", widget: "datetime", required: false }
              - { label: "Event Description", name: "event-description", widget: "markdown" }

      - label: "People"
        name: "people"
        file: "content/people.md"
        fields:
          - { label: "Path", name: "path", widget: "string" }
          - { name: "header", label: "Header", widget: "markdown" }
          - { name: "footer", label: "Footer", widget: "markdown" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Team"
            name: "team"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
              - { label: "Position", name: position, widget: "string" }
              - { label: "Profile Image", name: "photo", widget: "image", required: false }
              - { label: "Link", name: "link", widget: "string", required: false }

      - label: "Environment"
        name: "environment"
        file: "content/environment.md"
        fields:
          - { label: "Path", name: "path", widget: "string" }
          - { label: "Header", name: "header", widget: "markdown" }
          - { label: "Footer", name: "footer", widget: "markdown" }
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - { label: "Title", name: "sectionTitle", widget: "string" }
              - { label: "Body", name: "sectionBody", widget: "markdown" }

      - label: "Donate"
        name: "donate"
        file: "content/donate.md"
        fields:
          - { label: "Path", name: "path", widget: "string" }
          - { label: "Header", name: "header", widget: "markdown" }
          - { label: "Footer", name: "footer", widget: "markdown" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Options"
            name: "donationOptions"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Amount", name: "amount", widget: "number" }

      - label: "Downloads"
        name: "downloads"
        file: "content/downloads.md"
        fields:
          - { label: "Path", name: "path", widget: "string" }
          - { label: "Header", name: "header", widget: "markdown" }
          - { label: "Footer", name: "footer", widget: "markdown" }
          - { label: "Latest Release Title", name: "latestTitle", widget: "string" }
          - { label: "Latest Release Intro", name: "latestIntro", widget: "markdown" }
          - { label: "Latest Release Date", name: "latestDate", widget: "datetime" }
          - label: "Latest Releases"
            name: "latestDownloadOptions"
            widget: "list"
            fields:
              - { label: "Operating System", name: "os", widget: "select", options: ['Windows', 'Linux', 'Mac OS X'] }
              - { label: "Operating System Architecture", name: "osa", widget: "select", options: ['32-bit', '64-bit', 'Universal'] }
              - { label: "Link", name: "link", widget: "string" }
          - { label: "Stable Release Title", name: "stableTitle", widget: "string" }
          - { label: "Stable Release Intro", name: "stableIntro", widget: "markdown" }
          - { label: "Stable Release Date", name: "stableDate", widget: "datetime" }
          - label: "Stable-Releases"
            name: "stableDownloadOptions"
            widget: "list"
            fields:
              - { label: "Operating System", name: "os", widget: "select", options: ['Windows', 'Linux', 'Mac OS X'] }
              - { label: "Operating System Architecture", name: "osa", widget: "select", options: ['32-bit', '64-bit', 'Universal'] }
              - { label: "Link", name: "link", widget: "string" }
          - { label: "Beta Release Title", name: "betaTitle", widget: "string" }
          - { label: "Beta Release Intro", name: "betaIntro", widget: "markdown" }
          - { label: "Beta Release Date", name: "betaDate", widget: "datetime" }
          - label: "Pre-Releases"
            name: "betaDownloadOptions"
            widget: "list"
            fields:
              - { label: "Operating System", name: "os", widget: "select", options: ['Windows', 'Linux', 'Mac OS X'] }
              - { label: "Operating System Architecture", name: "osa", widget: "select", options: ['32-bit', '64-bit', 'Universal'] }
              - { label: "Link", name: "link", widget: "string" }

  - name: "books"
    label: "Books"
    label_singular: "Book"
    folder: "content/books"
    create: true
    fields:
      - { name: "path", label: "Path", widget: "string" }
      - { name: "header", label: "Header", widget: "markdown" }
      - { name: "footer", label: "Footer", widget: "markdown" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "cover", label: "Cover", widget: "image" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "date", label: "Date Published", widget: "datetime" }
      - name: "links"
        label: "Links"
        widget: "list"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "url", label: "URL", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "library"
    label: "Libraries"
    label_singular: "Library"
    folder: "content/libraries"
    create: true
    fields:
      - { name: "path", label: "Path", widget: "string" }
      - { name: "header", label: "Header", widget: "markdown" }
      - { name: "footer", label: "Footer", widget: "markdown" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "builtIn", label: "Built-in", widget: "boolean", default: false }
      - name: "links"
        label: "Links"
        widget: "list"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "url", label: "URL", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "tags", label: "Tags", widget: "relation", collection: "examples", searchFields: ["title", "body"], valueField: "path", displayFields: ["name", "path"] }

  - name: "tools"
    label: "Tools"
    label_singular: "Tool"
    folder: "content/tools"
    create: true
    fields:
      - { name: "path", label: "Path", widget: "string" }
      - { name: "header", label: "Header", widget: "markdown" }
      - { name: "footer", label: "Footer", widget: "markdown" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "builtIn", label: "Built-in", widget: "boolean", default: false }
      - name: "links"
        label: "Links"
        widget: "list"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "url", label: "URL", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "tags", label: "Tags", widget: "relation", collection: "examples", searchFields: ["title", "body"], valueField: "path", displayFields: ["name", "path"] }

  - name: "tutorials"
    label: "Tutorials"
    label_singular: "Tutorial"
    folder: "content/tutorials"
    create: true
    fields:
      - { name: "path", label: "Path", widget: "string" }
      - { name: "header", label: "Header", widget: "markdown" }
      - { name: "footer", label: "Footer", widget: "markdown" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "banner", label: "Banner", widget: "image" }
      - { name: "thumbnail", label: "Thumbnail", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "examples"
    label: "Examples"
    label_singular: "Example"
    folder: "content/examples"
    create: true
    fields:
      - { name: "path", label: "Path", widget: "string" }
      - { name: "header", label: "Header", widget: "markdown" }
      - { name: "footer", label: "Footer", widget: "markdown" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "thumbnail", label: "Thumbnail", widget: "image", required: false }
      - { name: "code", label: "Code", widget: "file" }
      
  - name: "exhibition"
    label: "Exhibition"
    label_singular: "Entry"
    folder: "content/exhibition"
    create: true
    fields:
      - { name: "path", label: "Path", widget: "string" }
      - { name: "header", label: "Header", widget: "markdown" }
      - { name: "footer", label: "Footer", widget: "markdown" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "banner", label: "Banner", widget: "image" }
      - { name: "thumbnail", label: "Thumbnail", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "links", label: "Links" }